spring.application.name=api-gateway
server.port=8080

# Routes Spring Cloud Gateway MVC
spring.cloud.gateway.mvc.routes[0].id=joueur-service
spring.cloud.gateway.mvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/joueurs/**

spring.cloud.gateway.mvc.routes[1].id=dictionnaire-service
spring.cloud.gateway.mvc.routes[1].uri=http://localhost:8082
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/mots/**

spring.cloud.gateway.mvc.routes[2].id=partie-service
spring.cloud.gateway.mvc.routes[2].uri=http://localhost:8083
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/parties/**

spring.cloud.gateway.mvc.routes[3].id=statistiques-service
spring.cloud.gateway.mvc.routes[3].uri=http://localhost:8084
spring.cloud.gateway.mvc.routes[3].predicates[0]=Path=/statistiques/**
